routes:
  # Order Management Routes
  - id: order_service_routes
    uri: "/api/orders/*"
    upstream:
      type: roundrobin
      nodes:
        "wms-order-management:8080": 1
    plugins:
      limit-req:
        rate: 100
        burst: 50
        rejected_code: 429
        key: remote_addr
        key_type: "var"
        allow_degradation: false
  
  # Inventory Management - Locations Routes
  - id: inventory_locations_routes
    uri: "/api/inventory/locations/*"
    upstream:
      type: roundrobin
      nodes:
        "wms-inventory-management:8000": 1
    strip_uri: true
    upstream_path_regex_rewrite:
      regex: "^/api/inventory/locations/(.*)"
      replacement: "/locations/$1"
  
  # Inventory Management - Products Routes
  - id: inventory_products_routes
    uri: "/api/inventory/products/*"
    upstream:
      type: roundrobin
      nodes:
        "wms-inventory-management:8000": 1
    strip_uri: true
    upstream_path_regex_rewrite:
      regex: "^/api/inventory/products/(.*)"
      replacement: "/products/$1"
  
  # Inventory Management - Stock Routes
  - id: inventory_stock_routes
    uri: "/api/inventory/stock/*"
    upstream:
      type: roundrobin
      nodes:
        "wms-inventory-management:8000": 1
    strip_uri: true
    upstream_path_regex_rewrite:
      regex: "^/api/inventory/stock/(.*)"
      replacement: "/stock/$1"
