# Local development specific overrides

apisix:
  apisix:  # Admin API configuration for local development
    admin:
      type: NodePort
      nodePort: 30180
      # Allow access from any IP address for local development
      allow:
        ipList:
          - "0.0.0.0/0"
      credentials:
        admin: admin
        viewer: viewer

  
  # NodePort configuration for local development
  service:
    type: NodePort
    http:
      enabled: true
      nodePort: 30080

  # More permissive rate limit for local development
  config:
    apisix:
      rateLimit:
        requestsPerSecond: 1000  # Higher rate limit for local development

# Local service configurations
wmsRoutes:
  # Order Service local settings
  orderService:
    enabled: true
    host: "localhost"
    serviceName: "wms-main-order-service"
  
  # Inventory Service local settings
  inventoryService:
    enabled: true
    host: "localhost"
    serviceName: "wms-main-inventory-service" 