# Local development specific overrides

apisix:
  # NodePort configuration for local development
  gateway:
    type: NodePort
    http:
      enabled: true
      port: 80
      nodePort: 30080
  
  # Admin API configuration for local development
  admin:
    type: NodePort
    nodePort: 30180
  
  # More permissive rate limit for local development
  config:
    apisix:
      rateLimit:
        requestsPerSecond: 1000  # Higher rate limit for local development

# Local service configurations
wmsRoutes:
  # Order Service local settings
  orderService:
    host: "localhost"
    serviceName: "wms-main-order-service"
  
  # Inventory Service local settings
  inventoryService:
    host: "localhost"
    serviceName: "wms-main-inventory-service" 